(define (simpsons-rule f a b n)   
  (define (h a b n) (/ (- b a) n))
  (define (simpson-iter k)
    (cond ((= k 0)          (+ (f (+ a (* k (h a b n))))  (simpson-iter (+ k 1))))
          ((= k n)             (f (+ a (* k (h a b n)))))
          ((odd?  k )  (+ (* 4 (f (+ a (* k (h a b n))))) (simpson-iter (+ k 1))))
          ((even? k )  (+ (* 2 (f (+ a (* k (h a b n))))) (simpson-iter (+ k 1))))
    )
  )
  (* (/ (h a b n) 3) (simpson-iter 0))
)

;(define (test)
;  (simpsons-rule square 1 100 200)
;)
