(define (make-account balance secret-password)
  (define (withdraw amount)
    (if (>= balance amount)
	(begin (set! balance (- balance amount))
	  balance)
	"Insufficient funds"))
  (define (deposit amount)
    (begin (set! balance (+ balance amount))
           balance))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
	  ((eq? m 'deposit) deposit)
	  (else (error "Unknown request -- MAKE-ACCOUNT"  m))))
  (lambda (password message)
    (if (eq? secret-password password)
	(dispatch message)
        (lambda (x) "Incorrect password"))))

(define (test)
  (define acc1 (make-account 100 'hello))
  ((acc1 'hello 'deposit) 50)
  ((acc1 'goodbye 'deposit) 50))
