(define (make-account balance secret-password)
  (define (withdraw amount)
    (if (>= balance amount)
	(begin (set! balance (- balance amount))
	  balance)
	"Insufficient funds"))
  (define (deposit amount)
    (begin (set! balance (+ balance amount))
           balance))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
	  ((eq? m 'deposit) deposit)
	  (else (error "Unknown request -- MAKE-ACCOUNT"  m))))
  (lambda (password message)
    (if (eq? secret-password password)
	(dispatch message)
        (lambda (x) "Incorrect password"))))

(define (make-joint acc acc-password new-password)
  (lambda (password message)
    (if (or (eq? password acc-password) (eq? password new-password))
	(acc acc-password  message)
	(lambda (x) "Incorrect password"))))

(define (test)
  (define a (make-account 100 'hello))
  (define b (make-joint a 'hello 'goodbye))
  (display ((b 'hello 'withdraw) 50))(newline)
  (display ((b 'goodbye 'withdraw) 50))(newline))
