(define (add-streams s1 s2) (stream-map + s1 s2))
(define (integers-starting-from n)
  (cons-stream n (integers-starting-from (+ n 1))))
(define integers (integers-starting-from 1))
(define (partial-sums s) (add-streams s (cons-stream 0 (partial-sums s))))
