(define (make-account balance secret-password)
  (define unsuccessful-attempts 0)
  (define (withdraw amount)
    (if (>= balance amount)
	(begin (set! balance (- balance amount))
	  balance)
	"Insufficient funds"))
  (define (deposit amount)
    (begin (set! balance (+ balance amount))
           balance))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
	  ((eq? m 'deposit) deposit)
	  (else (error "Unknown request -- MAKE-ACCOUNT"  m))))
  (define call-the-cops (lambda (x) "The cops are coming"))
  (lambda (password message)
    (if (eq? secret-password password)
	(begin (set! unsuccessful-attempts 0)
	       (dispatch message))
	(begin (set! unsuccessful-attempts (+ unsuccessful-attempts 1))
	       (if (> unsuccessful-attempts 7)
		   call-the-cops
		   (lambda (x) "Incorrect password"))))))

(define (test)
  (define acc1 (make-account 100 'hello))
  (display ((acc1 'hello 'deposit) 50))(newline)
  (display ((acc1 'goodbye 'deposit) 50))(newline)
  (display ((acc1 'goodbye 'deposit) 50))(newline)
  (display ((acc1 'goodbye 'deposit) 50))(newline)
  (display ((acc1 'goodbye 'deposit) 50))(newline)
  (display ((acc1 'goodbye 'deposit) 50))(newline)
  (display ((acc1 'goodbye 'deposit) 50))(newline)
  (display ((acc1 'goodbye 'deposit) 50))(newline)
  (display ((acc1 'hello 'deposit) 50))(newline)
  (display ((acc1 'goodbye 'deposit) 50))(newline))
