(and (supervisor ?name (Bitdiddle Ben))
     (address ?name ?where))
(and (salary (Bitdiddle Ben) ?amt)
     (salary ?name           ?x)
     (lisp-value < ?x ?amt))
(and (supervisor ?name ?sup)
     (job ?sup ?job)
     (not (job ?sup (computer . ?_))))
